### ISSUE TITLE
jlcall hangs without error if there are multiple Julia installations

### ISSUE THREAD

**Issue by pdetrempe** [jondeuce/MATDaemon.jl#7]
I had multiple julia folders in my ~\AppData\Local\Programs directory on Windows, causing the runtime string [here](https://github.com/jondeuce/MATDaemon.jl/blob/6a1de76acd835991e24f07067dd8c43c59e5e380/api/jlcall.m#L486) to take up multiple lines (and therefore be invalid). Just a heads up that there's no warning/error for this behavior.

**Comment by jondeuce** [comment]
Thanks for the heads up! I didn't realize that `where` may return multiple executable paths.

What would be the expected behaviour in your opinion? I can either:

- a) silently use the first executable path returned by `where`,
- b) use the first executable path but additionally warn that multiple `julia` executables were found, or
- c) throw an error indicating that multiple `julia` executables were found on the path, and require that the user set the `'runtime'` flag explicitly.

My inclination is that (b) is the most convenient option.

**Comment by pdetrempe** [comment]
I agree that (b) makes the most sense. I didn't see the `runtime` option before, thanks!

**Comment by jondeuce** [comment]
Fixed in [latest commit](https://github.com/jondeuce/MATDaemon.jl/commit/364cd96dcf2dc44e834a7f119294d5b7831fe7f4).
