### ISSUE TITLE
zsh:1: command not found: julia [Mac]

### ISSUE THREAD

**Issue by 70Gage70** [jondeuce/MATDaemon.jl#8]
I put `jcall.m` into a folder, opened it, and ran
```matlab
jlcall('sort', {rand(2,5)}, struct('dims', int64(2)))
```
Immediately, it returns `zsh:1: command not found: julia`. This is confusing since `which julia` in the terminal returns `/opt/homebrew/bin/julia`. This appears to be related to a general issue with MATLAB with respect to [calling system commands](https://www.mathworks.com/matlabcentral/answers/107068-can-not-run-system-commands-from-matlab-mac-osx). 

What worked for me was replacing the function `try_find_julia_runtime()` with the following

```matlab
function runtime = try_find_julia_runtime()
    setenv('PATH','/opt/homebrew/bin')
    runtime = 'julia';
end
```

Obviously that's not a very generic solution but I'm not really a MATLAB expert.

**Comment by jondeuce** [comment]
Unfortunately I don't have access to a Mac to test this out, but yes that seems rather inconvenient.

From the referenced link, it seems like you probably should be able to run the `setenv` command in the console, so you shouldn't have to modify `try_find_julia_runtime()`. Or perhaps more conveniently, add the following line to your `startup.m` file:
- `setenv('PATH', [getenv('PATH') ':/opt/homebrew/bin']);`

Note that typically you want to append to the current `PATH` environment variable, not replace it entirely.

You also have the option to pass the Julia runtime path to `jlcall` explicitly:
- `jlcall('sort', {rand(2,5)}, struct('dims', int64(2)), 'runtime', '/opt/homebrew/bin/julia')`

This will override `try_find_julia_runtime()`. I should add an example highlighting this flag in the `README`, since this flag was also useful [in a previous issue](https://github.com/jondeuce/MATDaemon.jl/issues/7).

**Comment by 70Gage70** [comment]
Thanks for the detailed response, modifying `startup.m` seems like the best solution.
